name: Claude Self-Hosted Assistant

# This workflow uses your self-hosted runner with Claude Pro subscription
# No API key needed!

permissions:
  contents: write
  pull-requests: write
  issues: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  claude-respond:
    # Use self-hosted runner with claude-pro label
    runs-on: [self-hosted, claude-pro]
    
    # Only run if @claude is mentioned
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git
        run: |
          git config --global user.name "Claude Assistant"
          git config --global user.email "claude@assistant.local"
          
      - name: Extract Claude request
        id: extract
        run: |
          # Extract the comment body
          if [ "${{ github.event_name }}" = "issues" ]; then
            COMMENT="${{ github.event.issue.body }}"
            ISSUE_NUMBER="${{ github.event.issue.number }}"
          else
            COMMENT="${{ github.event.comment.body }}"
            if [ "${{ github.event_name }}" = "issue_comment" ]; then
              ISSUE_NUMBER="${{ github.event.issue.number }}"
            else
              ISSUE_NUMBER="${{ github.event.pull_request.number }}"
            fi
          fi
          
          # Remove @claude mention and extract the request
          REQUEST=$(echo "$COMMENT" | sed 's/@claude//g' | xargs)
          
          # Save for next step
          echo "request<<EOF" >> $GITHUB_OUTPUT
          echo "$REQUEST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          
      - name: Process with Claude
        id: claude
        run: |
          # Create a context file with repository info
          cat > context.txt << 'EOF'
          Repository: ${{ github.repository }}
          Issue/PR #: ${{ steps.extract.outputs.issue_number }}
          Event: ${{ github.event_name }}
          
          User request:
          ${{ steps.extract.outputs.request }}
          
          Please provide a helpful response to this GitHub issue/PR comment.
          If code changes are requested, provide clear suggestions or implementations.
          EOF
          
          # Use Claude CLI directly (your Pro subscription)
          echo "Processing request with Claude..."
          claude --max-turns 5 < context.txt > response.md
          
          # Check if response was generated
          if [ ! -s response.md ]; then
            echo "No response generated" > response.md
          fi
          
      - name: Post response to GitHub
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const response = fs.readFileSync('response.md', 'utf8');
            
            const issue_number = ${{ steps.extract.outputs.issue_number }};
            
            // Post the response as a comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: response
            });
            
  # Automatic PR review using Claude Pro
  claude-review:
    runs-on: [self-hosted, claude-pro]
    
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get PR diff
        run: |
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch
          git diff ${{ github.event.pull_request.base.sha }}..pr-branch > pr.diff
          
      - name: Review with Claude
        run: |
          cat > review_request.txt << 'EOF'
          Please review this pull request diff and provide feedback on:
          1. Code quality and best practices
          2. Potential bugs or issues
          3. Performance considerations
          4. Security concerns if any
          
          Be constructive and helpful in your feedback.
          
          PR Title: ${{ github.event.pull_request.title }}
          PR Description: ${{ github.event.pull_request.body }}
          
          Diff to review:
          EOF
          
          cat pr.diff >> review_request.txt
          
          # Use Claude CLI for review
          claude --max-turns 3 < review_request.txt > review.md
          
      - name: Post review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: `## Claude Code Review\n\n${review}`
            });