name: Claude Enhanced Minimal

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  claude-respond-minimal:
    runs-on: [self-hosted, claude-pro]
    if: >
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request' && github.event.pull_request && contains(github.event.pull_request.body, '@claude'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Git and GitHub CLI
        run: |
          git config --global user.name "Claude Assistant"
          git config --global user.email "claude@assistant.local"
          
      - name: Check if Claude should respond
        id: should_respond
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number || context.payload.pull_request?.number;
            if (!issue_number) {
              console.log('No issue/PR number found');
              return false;
            }
            
            // Check if current comment mentions @claude
            const currentComment = context.payload.comment?.body || context.payload.issue?.body || '';
            if (currentComment.includes('@claude')) {
              console.log('Claude mentioned in current comment');
              core.setOutput('issue_number', issue_number);
              core.setOutput('should_respond', 'true');
              return true;
            }
            
            console.log('Claude not engaged');
            core.setOutput('should_respond', 'false');
            return false;
          
      - name: Echo test
        run: |
          echo "Enhanced workflow triggered!"
          echo "Should respond: ${{ steps.should_respond.outputs.should_respond }}"