name: Claude Enhanced V2

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

on:
  issue_comment:
    types: [created]

jobs:
  claude-respond:
    runs-on: [self-hosted, claude-pro]
    
    if: contains(github.event.comment.body, '@claude')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Setup Environment
        run: |
          echo "/home/rosswolf/.npm-global/bin" >> $GITHUB_PATH
          mkdir -p $HOME/.claude/sessions
          mkdir -p artifacts
          
      - name: Get Issue Number
        id: get_issue
        run: |
          echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          
      - name: Check for repository parent session
        id: check_parent
        run: |
          PARENT_SESSION="parent-repo-castlebuilder"
          echo "Checking for repository-wide parent session: $PARENT_SESSION"
          
          if .github/scripts/session_manager.sh exists "$PARENT_SESSION" | grep -q "true"; then
            echo "Repository parent session exists"
            echo "parent_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Repository parent session does not exist"
            echo "parent_exists=false" >> $GITHUB_OUTPUT
          fi
          echo "parent_session=$PARENT_SESSION" >> $GITHUB_OUTPUT
          
      - name: Simple Response Test
        run: |
          echo "Enhanced V2 workflow completed!"
          echo "Parent exists: ${{ steps.check_parent.outputs.parent_exists }}"
          echo "Issue: ${{ steps.get_issue.outputs.issue_number }}"